### ISSUE TITLE
raedon hd6670 black screen 

### ISSUE THREAD

**Issue by fameshadow** [avail/idLogger#10]
hi i get raedon hd6670 black screen of if i use the idlogger i kepp a card error :(
![screenshot 22](https://user-images.githubusercontent.com/31637353/30040702-c76be2f8-91da-11e7-8042-05bf25c7a647.png)

[idLogger-game.txt](https://github.com/avail/idLogger/files/1275708/idLogger-game.txt)

**Comment by avail** [comment]
use idlogger, and extract the file attached into %appdata%\TeknoParrot
[SBUU_e2prom.zip](https://github.com/avail/idLogger/files/1279022/SBUU_e2prom.zip)
