### ISSUE TITLE
DumbJVSManager Stopped Working

### ISSUE THREAD

**Issue by Kickin2JZ** [avail/idLogger#4]
Hello I'm Having a Problem
I just transfer the files to the game folder for the Initial D Game
When i Run DumbJVSManager in Admin Mode and then start initial d game
then it said this DumbJVSManager Stopped Working
Please Help?

**Comment by Kickin2JZ** [comment]
[idLogger-game.txt](https://github.com/avail/idLogger/files/1133655/idLogger-game.txt)

**Comment by avail** [comment]
it dies somewhere in networking initialisation. it's not idLogger's fault for this crash.
