### ISSUE TITLE
Will this tool support Intel HD 4000 or ANY Intel HD Graphics?(4000 and over)

### ISSUE THREAD

**Issue by vus7294** [avail/idLogger#9]
I have this laptop and want to run Initial d.
i7 3632qm, HD 4000, 8gb Ram.
but idlogger doesn't do anything in my laptop.
**with this? green screen. without this? green screen.**
how about your comment for support intel hd graphics?
I want just run initial d or what at my laptop.

**Comment by avail** [comment]
only amd support is in right now. intel support requires much more work.

**Comment by vus7294** [comment]
Well, is this tool support intel hd at later?
intel hd graphics support is pretty nice idea, so i send you for this request.
Good luck for you. Thanks.
